cypress/fixtures/about_us_view_sections.json
cypress/integration/visitorCanNavigateBetweenSPAViews.feature.js
src/components/Section.jsx
src/modules/Sections.js
src/views/AboutView.jsx

PT: https://www.pivotaltracker.com/story/show/178911504
```
As a Charity
To build trustworthy brand
We want to display info About Us
``` 
- About view useEffect fetches data for sections and saves it in local state
- map Background and Setup section component

Create About view

---

cypress/fixtures/search_results_football.json
cypress/integration/visitorCanNavigateBetweenSPAViews.feature.js
package.json
src/components/Map.jsx
src/components/MapMarker.jsx
src/components/ScreenSplit.jsx
src/components/ServiceListing.jsx
src/components/ServiceSearch.jsx
src/data/mapStyles.js
src/views/IndexView.jsx
src/views/ServiceSearchView.jsx
yarn.lock

PT: https://www.pivotaltracker.com/story/show/178908805
```
As a User
To be able to know where services are located
I want to see them displayed on the map
```
- adds Map and MapMarker components
- places marker for services that have geolocation
- refactors common page layout to SplitScreen component
-react-google-maps

Display Search results on Map

---

cypress/fixtures/services_view_section.json
cypress/integration/visitorCanNavigateBetweenSPAViews.feature.js
src/modules/Sections.js
src/views/ServicesView.jsx

PT: https://www.pivotaltracker.com/story/show/178961879
- extracts request for services data to Sections module
- renames route param in Sections module

extract all API calls to separate module

---

README.md
cypress/fixtures/about_self_care_view_sections.json
cypress/integration/visitorCanSeeAboutSelfCareView.js
cypress/integration/visitorCanSeeAboutSelfCareViewPage.feature.js
src/Routes.jsx
src/components/ApplicationFooter.jsx
src/components/ApplicationHeader.jsx
src/views/AboutSelfCareView.jsx
src/views/AboutUsView.jsx

PT: https://www.pivotaltracker.com/story/show/178911770
```
As a Charity
To inform visitor about benefits of Self Care
We need a section telling about it
```
- create `AboutSelfCare` view
- adds `/about/self_care` route
- maps necessary Sections onto this view
https://user-images.githubusercontent.com/79849155/127158270-76f3132d-81cf-4e7b-bbea-f4a243cf016a.mp4

Add view About Self Care and Social Prescribing

---

README.md
cypress.json
cypress/fixtures/app_data.json
cypress/integration/visitorCanNavigateBetweenSPAViews.feature.js
cypress/integration/visitorCanNavigateContactView.feature.js
cypress/integration/visitorCanSearchForServices.feature.js
cypress/integration/visitorCanSeeAboutSelfCareView.js
src/Routes.jsx
src/components/ApplicationHeader.jsx
src/components/ContactUs.jsx
src/components/TestimonialSlider.jsx
src/state/reducers/rootReducer.js
src/state/store/initialState.js
src/theme/kcscTheme.js
src/views/ContactView.jsx

```
As a charity
To communicate with our visitors
We want to give them ability to contact us
```
###
Requested changes
- Add appData initial state
- Update root reducer to be appData instead of testimonials so we can get contact information
- Update testimonials fixture to app_data so it includes contacts as well
- Add contact view
https://recordit.co/zAsPMmwKZh

Add Contact view component

---

cypress/fixtures/news_view_articles.json
cypress/integration/visitorCanNavigateUsingHeader.feature.js
cypress/integration/visitorCanSeeNewsView.feature.js
src/Routes.jsx
src/components/ApplicationHeader.jsx
src/components/Articles/Article.jsx
src/modules/Articles.js
src/views/NewsView.jsx

PT: https://www.pivotaltracker.com/story/show/178910086
```
As a Charity
To have our Users updated on Self Help and Healthcare
We want to display relevant news from that field
```
- adds NewsView and Article components
- adds `/info/news` route
- fetches news articles from `/api/articles`
- displays list of articles with most recent as a hero
https://user-images.githubusercontent.com/79849155/127467849-1cd2858e-1aae-4593-bdd3-7e8e5532d171.mp4

Add News view

---

README.md

PT: https://www.pivotaltracker.com/story/show/179056483

updates README with API requests, routes and responses

---

README.md
cypress/fixtures/app_data.json
cypress/integration/desktop/visitorCanNavigateBetweenSPAViews.feature.js
cypress/integration/mobile/landscape/visitorCanNavigateBetweenSPAViews.feature.js
cypress/integration/mobile/visitorCanNavigateBetweenSPAViews.feature.js
src/components/ApplicationFooter.jsx
src/state/store/initialState.js

PT: https://www.pivotaltracker.com/story/show/178950487

Fetch Footer data from API

---

README.md
cypress/fixtures/search_all_services.json
cypress/integration/desktop/desktopVisitorCanSearchForServices.feature.js
cypress/integration/mobile/landscape/landscapeVisitorCanSearchForServices.feature.js
cypress/integration/mobile/portraitVisitorCanSearchForServices.feature.js
src/components/Navbar/ApplicationHeader.jsx
src/components/Navbar/Navbar.jsx
src/components/ServiceListing.jsx
src/components/ServiceSearch.jsx
src/modules/Search.js

PT: https://www.pivotaltracker.com/story/show/178908732
```
As a user
To narrow down my search
I want to be able to filter it by SC category
```
- add Advances checkbox to search bar
- checkbox toggles visibility of category dropdown
- checkbox is not visible on landingpage
- fixes Application Header responsivness
https://user-images.githubusercontent.com/79849155/128150221-aebc7469-b89f-4b58-a9ce-f8247e5ec01c.mp4

Update Search for Services with category dropdown (only UI)

---

src/components/App.jsx
src/components/Section/SectionCenter.jsx
src/components/Section/SectionNoImage.jsx
src/components/Section/SectionRegular.jsx
src/components/Section/SectionSelector.jsx
src/components/Section/SectionWide.jsx
src/views/AboutSelfCareView.jsx
src/views/AboutUsView.jsx

- Add makeStyles to ```SectionNoImage.jsx```
- Remove padding on conteiner in ```App.jsx```
- Add id to ```SectionNoImage.jsx```
https://recordit.co/Cbzc2tHHsa

Update About sections to be more responsive

---

cypress/integration/desktop/desktopVisitorCanNavigateBetweenSPAViews.feature.js
src/components/ApplicationFooter.jsx
src/components/MessageModal.jsx
src/components/ServiceSearch.jsx
src/components/SubscribeToKCSC.jsx
src/modules/Inquiries.js
src/state/reducers/rootReducer.js

PT: https://www.pivotaltracker.com/story/show/178899422
```
As a charity
To keep users updated about us
We want them to be able to subscribe to our news letter
```
- adds subscribe to KCSC form to footer

Add `subscribe to KCSC` form to the Footer

---

src/components/Testimonial.jsx
src/data/fixtures/app_data.json
src/data/fixtures/testimonial_maggie_black.json
src/data/fixtures/testimonial_richard_erricson.json
src/modules/Articles.js

PT: https://www.pivotaltracker.com/story/show/179163287
```
Clicking learn more on testimonial leads to full story.
```

Adds articles to testimonials

---

cypress/integration/desktop/desktopVisitorCanNavigateBetweenSPAViews.feature.js
cypress/integration/desktop/desktopVisitorCanNavigateServicesView.feature.js
cypress/integration/desktop/desktopVisitorCanSeeInformationView.feature.js
cypress/integration/desktop/desktopVisitorCanSeeNewsView.feature.js
cypress/integration/mobile/landscape/landscapeVisitorCanNavigateBetweenSPAViews.feature.js
cypress/integration/mobile/landscape/landscapeVisitorCanNavigateServicesView.feature.js
cypress/integration/mobile/landscape/landscapeVisitorCanNavigateUsingHeader.feature.js
cypress/integration/mobile/portraitVisitorCanNavigateBetweenSPAViews.feature.js
cypress/integration/mobile/portraitVisitorCanNavigateServicesView.feature.js
cypress/integration/mobile/portraitVisitorCanNavigateUsingHeader.feature.js
src/data/fixtures/app_data.json
src/data/fixtures/information_items.json
src/data/fixtures/news_view_articles.json
src/data/fixtures/services_view_section.json

- Replace lorem ipsum's on site with "real" text

Replace Lorem Ipsums

---

src/components/Navbar/ApplicationHeader.jsx
src/modules/AdaptiveHelper.js

PT: https://www.pivotaltracker.com/story/show/179045455
```
Refactor Nav Menu so active Tabs are selected when navigating with routes
```
- active tab is selected by the current route
- styling of tabs changed so they are smaller
- header logo redirects to /home

Fix active tab selection

---

.gitignore
package.json
src/components/ScreenSplit.jsx
src/components/TestimonialSlider.jsx
src/views/IndexView.jsx
yarn.lock

- Add local tunnle package (https://www.npmjs.com/package/localtunnel)
https://recordit.co/8orpJuhNuR

Fix overlapping issue on landing page

---

src/components/Navbar/ApplicationHeader.jsx
src/components/Section/SectionRegular.jsx
src/components/ServiceListItem.jsx
src/components/ServiceSearch.jsx
src/data/fixtures/services_view_section.json

PT: https://www.pivotaltracker.com/story/show/179232641
- Adds error is performing search with empty query
- Adds a "Read more" to the accordion
- Adds a key listener for ENTER on the search bar
- Fixes link in "Find self care service" button

Fix search for services view

---

src/components/ApplicationFooter.jsx
src/components/SubscribeToKCSC.jsx

Align text to left
Lower size of footer logo
Add more space to bottom text
https://recordit.co/0WAfS4byuZ

Fix footer scrollable text

---

cypress/fixtures/about_us_view_sections.json
cypress/fixtures/services_view_section.json
cypress/integration/desktop/desktopVisitorCanNavigateServicesView.feature.js
cypress/integration/mobile/landscape/landscapeVisitorCanNavigateServicesView.feature.js
cypress/integration/mobile/portraitVisitorCanNavigateServicesView.feature.js
src/components/Navbar/ApplicationHeader.jsx
src/components/Section/CarouselCard.jsx
src/components/Section/SectionRegular.jsx
src/data/fixtures/about_us_view_sections.json
src/data/fixtures/services_view_section.json

PT: https://www.pivotaltracker.com/story/show/179163157
- fixes Services Scroll bug
- external links open in new tab

External links open new tab

---

src/components/Navbar/ApplicationHeader.jsx
src/modules/AdaptiveHelper.js

PT: https://www.pivotaltracker.com/story/show/179237097
- removes extra currentUrl declaration
- adds /services/search case to active tab selection

extra var declaration due to merging

---

cypress/fixtures/app_data.json
cypress/fixtures/information_items.json
cypress/fixtures/news_view_articles.json
cypress/fixtures/services_view_section.json
cypress/integration/desktop/desktopVisitorCanNavigateServicesView.feature.js
cypress/integration/desktop/desktopVisitorCanSearchForServices.feature.js
cypress/integration/desktop/desktopVisitorCanSeeErrorView.feature.js
cypress/integration/mobile/landscape/landscapeVisitorCanNavigateServicesView.feature.js
cypress/integration/mobile/portraitVisitorCanNavigateServicesView.feature.js
src/Routes.jsx
src/components/App.jsx
src/components/MessageModal.jsx
src/modules/AppData.js
src/modules/Articles.js
src/modules/Functions.js
src/modules/Information.js
src/modules/Inquiries.js
src/modules/Search.js
src/modules/Sections.js
src/state/reducers/rootReducer.js
src/state/store/initialState.js
src/views/ErrorView.jsx
src/views/IndexView.jsx

PT: https://www.pivotaltracker.com/story/show/178911376
```
As a Dev team
To keep user informed if something went wrong
We need to display error message
```
- adds redirect to error view if layout cannot be loaded
- adds error state to message modal
- adds error modal popup to services search

Add Error handling to requests

---

src/components/App.jsx
src/components/Navbar/MobileApplicationHeader.jsx
src/views/LoadingScreen.jsx

```
As a user
In order to to get a more pleasant experience 
i want to be met by a loading screen while content is loading
```
- Add Loading screen
- Change mobile nav to "white"

Loading Screen

---

README.md
cypress/fixtures/app_data.json
cypress/integration/mobile/landscape/landscapeVisitorCanNavigateUsingHeader.feature.js
cypress/integration/mobile/portraitVisitorCanNavigateUsingHeader.feature.js
src/components/Navbar/MobileApplicationHeader.jsx
src/data/fixtures/app_data.json
src/theme/mobileNavTheme.js

- make mobile nav links clickable for full width 
- fix mobile nav news and info to be accessible on mobile
https://recordit.co/kiP28tbLFa

Update mobile nav links

---

cypress/integration/desktop/desktopVisitorCanSearchForServices.feature.js
package.json
src/components/Service.jsx
src/components/ServiceListItem.jsx
yarn.lock

PT story: https://www.pivotaltracker.com/story/show/179251261
- adds first sentence of main description as preview
- on show more, preview is hidden 
- updates website to be link 
- link opens in new tab

Add description to services in search view

---

.semahpore/semaphore.yml
README.md
cypress/fixtures/app_data.json
cypress/integration/visitorCanNavigateUsingHeader.feature.js
cypress/integration/visitorCanSeeInformationView.feature.js
cypress/integration/visitorCanSeeNewsView.feature.js
cypress/integration/visitorCanSeeSingleArticle.feature.js
src/Routes.jsx
src/components/Articles/Article.jsx
src/components/Testimonial.jsx
src/data/fixtures/app_data.json
src/modules/AdaptiveHelper.js

PT: https://www.pivotaltracker.com/story/show/179354089

Change route /info/news to /news_info/news

---

src/modules/AppData.js
src/modules/Articles.js
src/modules/Information.js
src/modules/Inquiries.js

PT: https://www.pivotaltracker.com/story/show/179248750

engage real API calls (Client User)

---

src/components/Testimonial.jsx
src/data/fixtures/app_data.json

PT https://www.pivotaltracker.com/story/show/179415624

Fix links in testimonials

---

src/components/ApplicationFooter.jsx
src/modules/AppData.js

PT: https://www.pivotaltracker.com/story/show/179418084

fixes disclaimers typo

---

src/components/ApplicationFooter.jsx
src/components/Section/CarouselCard.jsx
src/components/Section/SectionCarousel.jsx

PT: https://www.pivotaltracker.com/story/show/179431072
- Also fixes footer 3rd column growing
https://user-images.githubusercontent.com/79849155/131653713-a66a4074-456a-4c26-a4ab-7f4dcc247f3a.mp4

Remove carousel, use cards for orgs instead 

---

cypress/fixtures/app_data.json
cypress/integration/visitorCanNavigateBetweenSPAViews.feature.js
package.json
src/data/fixtures/app_data.json
src/theme/serviceSearchTheme.js
src/views/IndexView.jsx
yarn.lock

pt: story : https://www.pivotaltracker.com/story/show/179431021
Updates tag line to requested. 
- adds it to app data call, to be editable in admin page

Fixes tagline changes

---

src/components/Service.jsx
src/components/ServiceListing.jsx
src/components/ServiceSearch.jsx
src/components/Testimonial.jsx
src/modules/Search.js

PT: https://www.pivotaltracker.com/story/show/179431289
- Message saying no map available for this service
- move button for show on map to under show less button in service list
- remove orange border around testimonials
- More subtle error message on search functionality

Small changes requested by client 

---

src/components/Information/InformationCard.jsx
src/components/Information/InformationItem.jsx

pt story: https://www.pivotaltracker.com/story/show/179434757
Opens new tab on clicking an information snippet

Information snippets to open new tabs

---

src/components/Navbar/ApplicationHeader.jsx
src/components/Navbar/MobileApplicationHeader.jsx
src/components/Section/SectionCenter.jsx
src/views/IndexView.jsx
src/views/ServicesView.jsx

PT: https://www.pivotaltracker.com/story/show/179460983

fix scrolling issue on public client

---

src/components/Service.jsx

PT: https://www.pivotaltracker.com/story/show/179463572

disables show on map button if no coords are availible

---

src/components/Section/SectionCenter.jsx
src/theme/centerSectionTheme.js

- Move theme to own file
- Fix image size issue
- Lower font sizes
https://recordit.co/03Fo0fWnC1

Fix center section image issue

---

src/components/TestimonialSlider.jsx
src/modules/Articles.js
src/modules/Information.js
src/views/InformationView.jsx

PT: https://www.pivotaltracker.com/story/show/179475229

tagline and testimonial bugs (Admin and Client)

---

README.md
cypress/fixtures/about_us_view_sections.json
cypress/fixtures/information_items.json
cypress/integration/visitorCanNavigateBetweenSPAViews.feature.js
cypress/integration/visitorCanNavigateUsingHeader.feature.js
cypress/integration/visitorCanSearchForServices.feature.js
cypress/integration/visitorCanSeeErrorView.feature.js
cypress/integration/visitorCanSeeInformationView.feature.js
src/components/Testimonial.jsx
src/data/fixtures/about_us_view_sections.json
src/modules/Sections.js

- update the fixture/readme of info to match api
- fix failing test 
- fix warnings in console
- replace smarta image to a working image

Fix warnings and tests User Client

---

src/components/Articles/Article.jsx
src/modules/Articles.js
src/views/ArticleView.jsx
src/views/NewsView.jsx

PT: https://www.pivotaltracker.com/story/show/179508723

Engage api calls for articles

---

src/components/ServiceSearch.jsx
src/modules/Search.js

PT: https://www.pivotaltracker.com/story/show/179524200

removes condition on empty querry

---

cypress/fixtures/single_article.json
cypress/integration/visitorCanNavigateBetweenSPAViews.feature.js
cypress/integration/visitorCanNavigateServicesView.feature.js
cypress/integration/visitorCanNavigateUsingHeader.feature.js
cypress/integration/visitorCanSeeInformationView.feature.js
cypress/integration/visitorCanSeeNewsView.feature.js
src/components/Section/SectionRegular.jsx
src/views/InformationView.jsx
src/views/NewsView.jsx

- Update fixture to match api (author.name)
- Refactor regular section button redirect function
- Update test to test on href instead of redirecting
- Add cleanup function in news view to fix leak warning

Run tests and fix failing ones

---

src/views/ArticleView.jsx

- adds condition to article body render to avoid passing undefined body to parse function

Fixes parsing error from undefined body

---

src/views/InformationView.jsx

PT: https://www.pivotaltracker.com/story/show/179748829
- removes pinned info and other info headers

Remove info view headers

---

src/components/Testimonial.jsx

PT: https://www.pivotaltracker.com/story/show/179749525
- replaces Link component to href to handle case if full link is provided

Admin testimonials if provided full link it redirects to invalid link

---

src/components/Navbar/ApplicationHeader.jsx
src/modules/AdaptiveHelper.js

PT: https://www.pivotaltracker.com/story/show/179748954
- replaces case statement in AdaptiveHelper with more versatile function

[ BUG ] single article view main tab navigation highlights HOME tab

---

cypress/integration/visitorCanNavigateBetweenSPAViews.feature.js
src/components/ApplicationFooter.jsx
src/components/Navbar/ApplicationHeader.jsx
src/modules/AdaptiveHelper.js

PT: https://www.pivotaltracker.com/story/show/179748945
- Sets parent (active main tab) using current route parsing in AdaptiveHelper instead of onClick function on main tab

[ BUG ] If using footer navigation it do not update secondary tabs

---

src/components/Information/InformationCard.jsx
src/components/Information/InformationItem.jsx
src/views/InformationView.jsx

PT: https://www.pivotaltracker.com/story/show/179763106
- fixes info snippets responsiveness
- styles info snippets to have fixed height

Restyles info snippets to have fixed height

---

cypress/integration/visitorCanNavigateBetweenSPAViews.feature.js
cypress/integration/visitorCanNavigateUsingHeader.feature.js
cypress/integration/visitorCanSeeAboutSelfCareView.js
cypress/integration/visitorCanSeeInformationView.feature.js
src/components/Section/SectionCenter.jsx
src/modules/Sections.js
src/views/AboutSelfCareView.jsx
src/views/AboutUsView.jsx
src/views/InformationView.jsx
src/views/ServicesView.jsx

- adds rea API calls for section index action
- adds stubs to tests for new functionality

Engage sections requests for api index

---

cypress/integration/visitorCanNavigateBetweenSPAViews.feature.js
src/components/TestimonialSlider.jsx

pt story: https://www.pivotaltracker.com/story/show/179815809 
Slider length when using left arrow was fixed to 2.

testimonial slider left arrow issue

---

cypress/integration/visitorCanNavigateBetweenSPAViews.feature.js
cypress/integration/visitorCanNavigateContactView.feature.js
src/components/ContactForm.jsx

Removes purpose of contact input on form 
fixes tests.

Small fixes on contact us page

---

cypress/fixtures/app_data.json
cypress/integration/visitorCanNavigateBetweenSPAViews.feature.js
package.json
src/components/Information/InformationCard.jsx
src/components/Information/InformationItem.jsx
src/components/Section/SectionRegular.jsx
src/components/Testimonial.jsx
src/modules/AdaptiveHelper.js
yarn.lock

PT: https://www.pivotaltracker.com/story/show/179779898
- adds helper function AdaptiveHelper.handleRedirect
- adds it to components to condition so if internal link redirect open in same tab if external in new tab
- url-parse (do parse incoming url from string to object)

Refactor redirect's target handling

---

src/components/Section/CarouselCard.jsx

Fix links in cards

---

src/components/Navbar/ApplicationHeader.jsx

- Make it only look for news_info in UR

news secondary navigation white

---

cypress/fixtures/case_study_view.json
cypress/fixtures/news_view_articles.json
cypress/integration/visitorCanSeeCaseStudies.feature.js
src/Routes.jsx
src/components/Articles/Article.jsx
src/modules/CaseStudies.js
src/theme/kcscTheme.js
src/views/ArticleView.jsx
src/views/CaseStudiesView.jsx
src/views/NewsView.jsx
yarn.lock

```
As an Owner
Not to confuse people
I want a separate view for case studies
```
- Add route about/case_studies
- Add case studies view
- Add CaseStudies module

Add view for all case studies

---

cypress/fixtures/app_data.json
cypress/fixtures/case_study_view.json
cypress/fixtures/single_article.json
cypress/fixtures/single_case_study.json
cypress/integration/visitorCanSeeCaseStudies.feature.js
cypress/integration/visitorCanSeeSingleCaseStudy.feature.js
src/Routes.jsx
src/components/CaseStudies/CaseStudyArticle.jsx
src/data/fixtures/app_data.json
src/data/fixtures/single_article.json
src/data/fixtures/testimonial_maggie_black.json
src/data/fixtures/testimonial_richard_erricson.json
src/modules/AdaptiveHelper.js
src/modules/CaseStudies.js
src/views/ArticleView.jsx
src/views/CaseStudiesView.jsx
src/views/CaseStudyArticleView.jsx

```
As a visitor
To know more about CHWL
I want to read what their case studies say
```
- Update index action to fix map issue
- Add view for case study article
- Add case study to the navbar

Add view for individual case study
